require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe ConversationsController do

  # This should return the minimal set of attributes required to create a valid
  # Conversation. As you add validations to Conversation, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "theme" => "MyString"} }

  before :each do
    @owner =  FactoryGirl.create :user, conversations: []
    @users = [FactoryGirl.create(:user, conversations: []),
              FactoryGirl.create(:user, conversations: []),
              @owner]
    request.accept = 'application/json'
  end

  describe "GET index" do
    it "assigns all conversations as @conversations for owner" do
      @owner.conversations.create! users: @users
      sign_in @owner
      get :index, {}
      assigns(:conversations).should eq(@owner.reload.conversations)
    end

    it 'assigns all conversations as @conversations for not owner' do
      @owner.conversations.create! users: @users
      sign_in @users.first
      get :index, {}
      assigns(:conversations).should eq(@users.first.reload.conversations)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Conversation" do
        sign_in @owner
        expect {
          post :create, {conversation: valid_attributes}
        }.to change(Conversation, :count).by(1)
      end

      it "assigns a newly created conversation as @conversation" do
        sign_in @owner
        post :create, conversation: valid_attributes
        assigns(:conversation).should be_a(Conversation)
        assigns(:conversation).should be_persisted
      end
    end
  end

end
